### ISSUE TITLE
translation / i18n

### ISSUE THREAD

**Issue by edzillion** [bohemeyer/meingrundeinkommen#4]
Hi

My name is Ed, and I was at a lecture by one of your compatriots, Amira Jehia, at the [Basic Income Ireland Summer Forum](http://us8.campaign-archive2.com/?u=7f07fe37484ef8e6db4eda2c4&id=d7f4d9464d&e=58f675cb50) a couple of weeks ago. I was most impressed by the progress you guys have made and after her lecture we got into a discussion about the feasiblity of bringing the Mein Grundeinkommen project to Ireland. 

I think if we go down the route of taking your code / site and translating it, what we should do is refactor with a view to allowing others to translate it into more languages easily. So some kind of internationalisation process of changing string literals into insertion hooks or something.

I am no expert on this, but I can manage the project. First I need to get a better idea of how your site works and what it does. Would you be able to write an overview of what is happening, what techs are being used, what your build process is etc.? That would be useful for a start.

regards
ed

**Comment by edzillion** [comment]
OK had a look around I see you have some i18n stuff here:

https://github.com/bohemeyer/meingrundeinkommen/blob/master/client/languages/deDE.json

I am having a friend look through the code and will get a better idea of how to proceed.

**Comment by ZengineChris** [comment]
Hi Ed,

we got your message and get in touch with you as soon as possible.
